; This file describes fixture build properties

[fixtures]
timestamp = 2025-06-03T16:52:10.738098
command_line_args = fill -c pytest.ini -v tests/prague/eip7702_set_code_tx --fork=Prague -m state_test

[packages]
pytest = 8.3.5
pluggy = 1.5.0

[plugins]
html = 4.1.1
regex = 0.2.0
xdist = 3.6.1
json-report = 1.5.0
metadata = 3.1.1
custom-report = 1.0.1

[tools]
eels resolutions = /home/rodi/rodibozman/execution-spec-tests/eels_resolutions.json
t8n = ethereum-spec-evm-resolver 0.0.5
solc = 0.8.24

[environment]
python = 3.10.12
platform = Linux-6.8.0-60-generic-x86_64-with-glibc2.35

